version: '3.6'
services:
  zeh_challenge_db:
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
    image: postgis/postgis
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
  zeh_challenge_api:
    build: .
    depends_on:
      - zeh_challenge_db
    environment:
      MIX_ENV: dev
    env_file:
      - .env
    ports:
      - 4000:4000
    volumes:
      - .:/app
volumes:
  pgdata: